services:
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: go_web
    volumes:
      - .:/app
    ports:
      - "${WEB_PORT}:3000"
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: go_crud
      DATABASE_PORT: 5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
