version: '3'

tasks:
  up:
    cmds:
      - 'docker compose up --detach --remove-orphans {{.CLI_ARGS}}'

  down: 'docker compose down --remove-orphans {{.CLI_ARGS}}'

  rebuild:
    cmds:
      - task: down
      - 'docker compose build'
      - task: up

  lint: 'docker compose exec app golangci-lint run ./...'

  make-m: 'docker compose exec app migrate create -ext sql -dir db/migrations -seq create_users_table'

  migrate-m: 'docker compose exec app migrate -database $POSTGRESQL_URL -path db/migrations up'


