version: '3'

vars:
  GO: '{{if not .LOCALLY}}docker compose exec -it app{{end}}'

tasks:
  go: '{{.GO}} sh'

  up:
    cmds:
      - 'docker compose up --detach --remove-orphans {{.CLI_ARGS}}'

  down: 'docker compose down --remove-orphans {{.CLI_ARGS}}'

  rebuild:
    cmds:
      - task: down
      - 'docker compose build'
      - task: up

  lint: '{{.GO}} golangci-lint run ./...'

  make-m: '{{.GO}} migrate create -ext sql -dir db/migrations -seq create_users_table'
  m-up: '{{.GO}} migrate -database $POSTGRESQL_URL -path db/migrations up'
  m-down: '{{.GO}} migrate -database $POSTGRESQL_URL -path db/migrations down'


